@StonksAPI_HostAddress = https://localhost:7171


// A file for testing and documentation of backend API endpoints
// To try out, run visual studio project and then click "Send request"


GET {{StonksAPI_HostAddress}}/api/IBM?interval=daily
Accept: application/json
### 1. Fetches daily stock prices by ticker and interval 

GET {{StonksAPI_HostAddress}}/api/IBM?interval=weekly
Accept: application/json
### 2. Fetches weekly stock prices by ticker and interval 

GET {{StonksAPI_HostAddress}}/api/IBM/intraday?interval=60min
Accept: application/json
### 3. Fetches intraday hourly stock prices by ticker and interval 


POST {{StonksAPI_HostAddress}}/auth/register
Content-Type: application/json
{
    "Email": "jasiek2r@gmail.com",
    "Username": "test",
    "Password": "Odell@2024#",
    "ConfirmPassword":"Odell@2024#"
}

### 4. Registers an user account in the database


POST {{StonksAPI_HostAddress}}/auth/login
Content-Type: application/json
{
    "Email": "jasiek2r@gmail.com",
    "Password": "Odell@2024#"
}
### 5. Logs user in

POST {{StonksAPI_HostAddress}}/holdings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTc0MzQyMTY4OSwiaXNzIjoiaHR0cDovL3N0b2NrbWFya2V0YXBpLmgyai5jb20iLCJhdWQiOiJodHRwOi8vc3RvY2ttYXJrZXRhcGkuaDJqLmNvbSJ9.zGbp0LUcZ3kg9evLrhfDdQNkAxQ-yEvi6tbbeuRpNsk
Content-Type: application/json
{
  "Ticker": "IBM",
  "Name": "International Business Machines",
  "PurchasePrice": 120.00,
  "PurchaseAmount": 1.00
}
### 6. Creates a holding


GET {{StonksAPI_HostAddress}}/holdings/2
### 7. Sends a request to fetch holding by id (should return "401 Unauthorized")

GET {{StonksAPI_HostAddress}}/holdings/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTc0MzQyMTAzNywiaXNzIjoiaHR0cDovL3N0b2NrbWFya2V0YXBpLmgyai5jb20iLCJhdWQiOiJodHRwOi8vc3RvY2ttYXJrZXRhcGkuaDJqLmNvbSJ9.-USNz0fwJR7RlEKsue_dTRmH3tCumaI5kPWQrtlV9VI
### 8. Sends a request to fetch holding by id but with proper user token (should return "200 OK")

GET {{StonksAPI_HostAddress}}/holdings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTc0MzQyMTAzNywiaXNzIjoiaHR0cDovL3N0b2NrbWFya2V0YXBpLmgyai5jb20iLCJhdWQiOiJodHRwOi8vc3RvY2ttYXJrZXRhcGkuaDJqLmNvbSJ9.-USNz0fwJR7RlEKsue_dTRmH3tCumaI5kPWQrtlV9VI
### 9. Sends a request to fetch all holdings created by the current user

DELETE {{StonksAPI_HostAddress}}/holdings/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTc0MzQyMTY4OSwiaXNzIjoiaHR0cDovL3N0b2NrbWFya2V0YXBpLmgyai5jb20iLCJhdWQiOiJodHRwOi8vc3RvY2ttYXJrZXRhcGkuaDJqLmNvbSJ9.zGbp0LUcZ3kg9evLrhfDdQNkAxQ-yEvi6tbbeuRpNsk
### 10. Sends a request to delete holding by id but with proper user token (should return "200 OK" if holding exists)


GET {{StonksAPI_HostAddress}}/api/IBM/info
### 11. Fetches general information about an asset

GET {{StonksAPI_HostAddress}}/api/IBM/dividends
### 12. Fetches information about dividends of a given stock

GET {{StonksAPI_HostAddress}}/api/IBM/overview
### 12. Fetches overview of the company
